# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - nightly
notifications:
  email: false
matrix:
  fast_finish: true
after_success:
  - julia -e 'cd(Pkg.dir("FilePaths")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
